server:
  port: 8123
  servlet:
    context-path: /api
spring:
  application:
    name: fon-picture-backend
  profiles:
    active: local  # 激活 local profile，加载 application-local.yml
  servlet:
    multipart:
      # 单个文件最大大小
      max-file-size: 10MB
      # 请求最大大小（所有文件总和）
      max-request-size: 100MB
      # 是否启用文件上传
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fontal-picture
    username: root
    password: root
  data:
    redis:
      host: 127.0.0.1
      database: 2
      port: 6379
      connect-timeout: 5000
  # Spring Session 配置
  session:
    store-type: redis  # 使用 Redis 存储 Session
    timeout: 2592000   # Session 过期时间（秒）30天 = 30 * 24 * 60 * 60

mybatis-plus:
  configuration:
    # MyBatis ??
    map-underscore-to-camel-case: false
    # ???????????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
# springdoc-openapi????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.fontal.fonpicturebackend.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn

# 第三方登入
